apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs

spec:
  replicas: 3
  selector:
     matchLabels:
       env: production
#    matchExpressions:
#     - {key: use , operator: In , values: [ production ]}
      
  template:
    metadata:
      name: myweb-pod
      labels:
        use: production
        
        
   
    spec:
      containers:
        - name: myweb-con
          image: httpd